import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import CardSkiils from '../components/CardSkills'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Symon Nascimento</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <CardSkiils/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/symon-nascimento"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Symon N Simon
        </a>
      </footer>
    </div>
  )
}

export default Home
